//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballPitchesBooking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballPitchesBooking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí này đang tồn tại quảng cáo đang hoạt động.
        /// </summary>
        internal static string Ads_ExistingAdvertisement {
            get {
                return ResourceManager.GetString("Ads_ExistingAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian quảng cáo đã kết thúc, xin vui lòng chọn thời gian quảng cáo khác.
        /// </summary>
        internal static string Ads_ExpiredTimeOver {
            get {
                return ResourceManager.GetString("Ads_ExpiredTimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ đang bận. Xin vui lòng thử lại sau.
        /// </summary>
        internal static string DB_Exception {
            get {
                return ResourceManager.GetString("DB_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string Delete_Success {
            get {
                return ResourceManager.GetString("Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy điền đầy đủ vào những trường thông tin bắt buộc.
        /// </summary>
        internal static string Form_EmptyFields {
            get {
                return ResourceManager.GetString("Form_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này đang bị khoá.
        /// </summary>
        internal static string Login_BlockUser {
            get {
                return ResourceManager.GetString("Login_BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này chưa được kích hoạt.
        /// </summary>
        internal static string Login_InactiveUser {
            get {
                return ResourceManager.GetString("Login_InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác, vui lòng đăng nhập email và kích hoạt tài khoản.
        /// </summary>
        internal static string Login_IncorrectPassword {
            get {
                return ResourceManager.GetString("Login_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        internal static string Login_IncorrectUserName {
            get {
                return ResourceManager.GetString("Login_IncorrectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không giống với xác nhận. Xin vui lòng nhập lại.
        /// </summary>
        internal static string Password_NotMatchWithConfirm {
            get {
                return ResourceManager.GetString("Password_NotMatchWithConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian khuyến mãi không đúng, vui lòng chọn thời gian khác.
        /// </summary>
        internal static string Promotion_TimeFromOverTo {
            get {
                return ResourceManager.GetString("Promotion_TimeFromOverTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian khuyến mãi đã kết thúc, xin vui lòng chọn thời gian kết thúc khác.
        /// </summary>
        internal static string Promotion_TimeOver {
            get {
                return ResourceManager.GetString("Promotion_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thứ hạng đã được sử dụng. Xin vui lòng chọn tên khác.
        /// </summary>
        internal static string Rank_RankNameNotAvailable {
            get {
                return ResourceManager.GetString("Rank_RankNameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm thứ hạng đã được sử dụng. Xin vui lòng chọn điểm khác.
        /// </summary>
        internal static string Rank_RankPointNotAvailable {
            get {
                return ResourceManager.GetString("Rank_RankPointNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng. Xin vui lòng chọn email khác.
        /// </summary>
        internal static string Reg_EmailNotAvailable {
            get {
                return ResourceManager.GetString("Reg_EmailNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        internal static string Reg_EmailWrongFormat {
            get {
                return ResourceManager.GetString("Reg_EmailWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đầy đủ yêu cầu từ 1 đến 50 kí tự.
        /// </summary>
        internal static string Reg_FullnameNotInLenght {
            get {
                return ResourceManager.GetString("Reg_FullnameNotInLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu yêu cầu từ 6 đến 32 kí tự.
        /// </summary>
        internal static string Reg_PasswordNotInLenght {
            get {
                return ResourceManager.GetString("Reg_PasswordNotInLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải từ 6 đến 20 kí tự.
        /// </summary>
        internal static string Reg_PhoneNumberNotInLenght {
            get {
                return ResourceManager.GetString("Reg_PhoneNumberNotInLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập chỉ được chữ và số.
        /// </summary>
        internal static string Reg_UserNamealphanumeric {
            get {
                return ResourceManager.GetString("Reg_UserNamealphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản đã được sử dụng. Xin vui lòng chọn tên khác.
        /// </summary>
        internal static string Reg_UserNameNotAvailable {
            get {
                return ResourceManager.GetString("Reg_UserNameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập yêu cầu từ 6 đến 32 ký tự.
        /// </summary>
        internal static string Reg_UserNameOutOfLength {
            get {
                return ResourceManager.GetString("Reg_UserNameOutOfLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời lượng đặt sân phải lớn hơn 1 giờ và không quá 3 giờ.
        /// </summary>
        internal static string Resv_DurationTimeOutOfRange {
            get {
                return ResourceManager.GetString("Resv_DurationTimeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sân đã được đặt, vui lòng chọn thời gian đặt sân khác.
        /// </summary>
        internal static string Resv_FieldIsNotAvailable {
            get {
                return ResourceManager.GetString("Resv_FieldIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu có đối thủ, vui lòng nhập đầy đủ thông tin đối thủ.
        /// </summary>
        internal static string Resv_NeedRivalException {
            get {
                return ResourceManager.GetString("Resv_NeedRivalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sân không phục vụ giờ này.
        /// </summary>
        internal static string Resv_NotInOpenTime {
            get {
                return ResourceManager.GetString("Resv_NotInOpenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kèo này đã có đối thủ, xin vui lòng chọn kèo khác.
        /// </summary>
        internal static string Resv_RivalAvailable {
            get {
                return ResourceManager.GetString("Resv_RivalAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian đặt sân phải muộn hơn thời gian hiện tại ít nhất 1 giờ.
        /// </summary>
        internal static string Resv_TimeOver {
            get {
                return ResourceManager.GetString("Resv_TimeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền hạn để quản lý sân bóng này.
        /// </summary>
        internal static string StadiumStaff_HaveNoPermissionTotAccessStadium {
            get {
                return ResourceManager.GetString("StadiumStaff_HaveNoPermissionTotAccessStadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một trong số những nhân viên mới thêm vào đã là nhân viên của sân này.
        /// </summary>
        internal static string StadiumStaff_UpdateStadiumNewStaffConflict {
            get {
                return ResourceManager.GetString("StadiumStaff_UpdateStadiumNewStaffConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai một trong những tên tài khoản được cấp quyền quản lý sân.
        /// </summary>
        internal static string StadiumStaff_UpdateStadiumUserNotFound {
            get {
                return ResourceManager.GetString("StadiumStaff_UpdateStadiumUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        internal static string Update_Success {
            get {
                return ResourceManager.GetString("Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình tải lên không đúng định dạng.
        /// </summary>
        internal static string Upload_NotImage {
            get {
                return ResourceManager.GetString("Upload_NotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài khoản này.
        /// </summary>
        internal static string User_UserNotMatched {
            get {
                return ResourceManager.GetString("User_UserNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài khoản chủ sân đã nhập.
        /// </summary>
        internal static string Webstaff_MainOwnerNotFound {
            get {
                return ResourceManager.GetString("Webstaff_MainOwnerNotFound", resourceCulture);
            }
        }
    }
}
