<?xml version="1.0" encoding="utf-8"?><Database Name="FootballPitchesBooking" Class="FPBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=FootballPitchesBooking;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FootballPitchesBookingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Advertisement" Member="Advertisements">
    <Type Name="Advertisement">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AdvertiseDetail" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Creator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Advertisement" Member="User" ThisKey="Creator" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Point" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RankId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Advertisement" Member="Advertisements" ThisKey="Id" OtherKey="Creator" Type="Advertisement" />
      <Association Name="User_JoinSystemRequest" Member="JoinSystemRequests" ThisKey="Id" OtherKey="UserId" Type="JoinSystemRequest" />
      <Association Name="User_Reservation" Member="Reservations" ThisKey="Id" OtherKey="UserId" Type="Reservation" />
      <Association Name="User_Reservation1" Member="Reservations1" ThisKey="Id" OtherKey="Approver" Type="Reservation" />
      <Association Name="User_Reservation2" Member="Reservations2" ThisKey="Id" OtherKey="RivalId" Type="Reservation" />
      <Association Name="User_Reservation3" Member="Reservations3" ThisKey="Id" OtherKey="RivalFinder" Type="Reservation" />
      <Association Name="User_Stadium" Member="Stadiums" ThisKey="Id" OtherKey="MainOwner" Type="Stadium" />
      <Association Name="User_StadiumDistance" Member="StadiumDistances" ThisKey="Id" OtherKey="UserId" Type="StadiumDistance" />
      <Association Name="User_StadiumRating" Member="StadiumRatings" ThisKey="Id" OtherKey="UserId" Type="StadiumRating" />
      <Association Name="User_StadiumReview" Member="StadiumReviews" ThisKey="Id" OtherKey="UserId" Type="StadiumReview" />
      <Association Name="User_StadiumReview1" Member="StadiumReviews1" ThisKey="Id" OtherKey="Approver" Type="StadiumReview" />
      <Association Name="User_StadiumStaff" Member="StadiumStaffs" ThisKey="Id" OtherKey="UserId" Type="StadiumStaff" />
      <Association Name="MemberRank_User" Member="MemberRank" ThisKey="RankId" OtherKey="Id" Type="MemberRank" IsForeignKey="true" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Field" Member="Fields">
    <Type Name="Field">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ParentField" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FieldType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PriceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Field_Field" Member="Fields" ThisKey="Id" OtherKey="ParentField" Type="Field" />
      <Association Name="Field_Promotion" Member="Promotions" ThisKey="Id" OtherKey="FieldId" Type="Promotion" />
      <Association Name="Field_Reservation" Member="Reservations" ThisKey="Id" OtherKey="FieldId" Type="Reservation" />
      <Association Name="Field_Field" Member="Field1" ThisKey="ParentField" OtherKey="Id" Type="Field" IsForeignKey="true" />
      <Association Name="FieldPrice_Field" Member="FieldPrice" ThisKey="PriceId" OtherKey="Id" Type="FieldPrice" IsForeignKey="true" />
      <Association Name="Stadium_Field" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FieldPrice" Member="FieldPrices">
    <Type Name="FieldPrice">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FieldPriceName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FieldPriceDescription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="FieldPrice_Field" Member="Fields" ThisKey="Id" OtherKey="PriceId" Type="Field" />
      <Association Name="FieldPrice_PriceTable" Member="PriceTables" ThisKey="Id" OtherKey="FieldPriceId" Type="PriceTable" />
      <Association Name="Stadium_FieldPrice" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JoinSystemRequest" Member="JoinSystemRequests">
    <Type Name="JoinSystemRequest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StadiumName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StadiumAddress" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_JoinSystemRequest" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MemberRank" Member="MemberRanks">
    <Type Name="MemberRank">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RankName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Promotion" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="MemberRank_User" Member="Users" ThisKey="Id" OtherKey="RankId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.PriceTable" Member="PriceTables">
    <Type Name="PriceTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldPriceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeFrom" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TimeTo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="FieldPrice_PriceTable" Member="FieldPrice" ThisKey="FieldPriceId" OtherKey="Id" Type="FieldPrice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotion" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PromotionFrom" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PromotionTo" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Creator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Promotion_Reservation" Member="Reservations" ThisKey="Id" OtherKey="PromotionId" Type="Reservation" />
      <Association Name="Field_Promotion" Member="Field" ThisKey="FieldId" OtherKey="Id" Type="Field" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PromotionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VerifyCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Approver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HasRival" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RivalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RivalName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RivalPhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RivalEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RivalFinder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Field_Reservation" Member="Field" ThisKey="FieldId" OtherKey="Id" Type="Field" IsForeignKey="true" />
      <Association Name="Promotion_Reservation" Member="Promotion" ThisKey="PromotionId" OtherKey="Id" Type="Promotion" IsForeignKey="true" />
      <Association Name="User_Reservation" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Reservation1" Member="User1" ThisKey="Approver" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Reservation2" Member="User2" ThisKey="RivalId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Reservation3" Member="User3" ThisKey="RivalFinder" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role" Member="Role1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="Id" OtherKey="RoleId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Stadium" Member="Stadiums">
    <Type Name="Stadium">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ward" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MainOwner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OpenTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CloseTime" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ExpiredDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Stadium_Field" Member="Fields" ThisKey="Id" OtherKey="StadiumId" Type="Field" />
      <Association Name="Stadium_FieldPrice" Member="FieldPrices" ThisKey="Id" OtherKey="StadiumId" Type="FieldPrice" />
      <Association Name="Stadium_StadiumDistance" Member="StadiumDistances" ThisKey="Id" OtherKey="StadiumId" Type="StadiumDistance" />
      <Association Name="Stadium_StadiumImage" Member="StadiumImages" ThisKey="Id" OtherKey="StadiumId" Type="StadiumImage" />
      <Association Name="Stadium_StadiumRating" Member="StadiumRatings" ThisKey="Id" OtherKey="StadiumId" Type="StadiumRating" />
      <Association Name="Stadium_StadiumReview" Member="StadiumReviews" ThisKey="Id" OtherKey="StadiumId" Type="StadiumReview" />
      <Association Name="Stadium_StadiumStaff" Member="StadiumStaffs" ThisKey="Id" OtherKey="StadiumId" Type="StadiumStaff" />
      <Association Name="User_Stadium" Member="User" ThisKey="MainOwner" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StadiumDistance" Member="StadiumDistances">
    <Type Name="StadiumDistance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Distance" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Stadium_StadiumDistance" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
      <Association Name="User_StadiumDistance" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StadiumImage" Member="StadiumImages">
    <Type Name="StadiumImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Caption" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Stadium_StadiumImage" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StadiumRating" Member="StadiumRatings">
    <Type Name="StadiumRating">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Stadium_StadiumRating" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
      <Association Name="User_StadiumRating" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StadiumReview" Member="StadiumReviews">
    <Type Name="StadiumReview">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewContent" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Approver" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Stadium_StadiumReview" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
      <Association Name="User_StadiumReview" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_StadiumReview1" Member="User1" ThisKey="Approver" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StadiumStaff" Member="StadiumStaffs">
    <Type Name="StadiumStaff">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StadiumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Stadium_StadiumStaff" Member="Stadium" ThisKey="StadiumId" OtherKey="Id" Type="Stadium" IsForeignKey="true" />
      <Association Name="User_StadiumStaff" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>